apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-cicd-dev
  
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: kube-cicd
        role: backend
        env: dev    
    spec:
      containers:
      - name: kube-cicd
        image: asia.gcr.io/gcp-projectid/kube-cicd:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 8009

 