---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-cicd-canary
 
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: kube-cicd
        role: backend
        env: prd     
    spec:
      containers:
      - name: kube-cicd
        image: asia.gcr.io/my-gcp101/kube-cicd:v1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 8009